### ISSUE TITLE
Enable Doxygen Documentation

### ISSUE THREAD

**Issue by bkochuna** [bkochuna/ners570f23-SpMV#10]
## Background

Documentation is always extremely helpful. However, it can also seem extremely daunting if it is put off for awhile and you wait to do it all at once. Fortunately, there is a tool Doxygen that can automatically create pretty formatted documentation in several formats (html, xml, LaTeX and pdf) by processing special markup comments in the source code.

This issue is about setting up the project to automatically create Doxygen documentation based on comments in the source code.

## Tasks
- [ ] Choose an appropriate output format for documentation
- [ ] Define standards for what information the documentation should have.
- [ ] Modify CMake build system to create a target for building documentation
- [ ] Configure doxygen file for project

## Definition of Done
When configuring the project, there is a make target for generating documentation. When executing the make target, the appropriately output documentation is produced. An example of that documentation output is attached somehwere in this issue (could be screen shot, could be file, could be link to somewhere else)
