### ISSUE TITLE
Add construction/destruction tests for the DEN matrix class

### ISSUE THREAD

**Issue by KyleVaughn** [bkochuna/ners570f23-SpMV#21]
## Description:
The purpose of this task is to create a unit test for the constructors and destructors that are used for allocation and destruction of memory for variables and objects in the DEN matrix class. 

## Tasks:
- [ ] Call the default constructor and ensure that objects have been created as per requirement. 
- [ ] Call our other parametrized constructors and ensure that all our variables have been initialized. 
- [ ] Since overloading is being incorporated, ensure that the program is correctly defined such that our constructor calls match properly. 
- [ ] Ensure that the constructor accepts inputs that are within our desired range of validity. 
- [ ] Once the previous step is done, we now send invalid inputs such as that of a null matrix or passing negative value for our array sizes to ensure that our constructors and destructors are capable of proper error handling and throwing the necessary errors. 
- [ ] Ensure that our constructors and destructors work properly with the correct data type and throw error if an incorrect data type is passed. 
- [ ] Ensure proper functioning of our pointers used to create our class object. and that our object gets destroyed after its creation and usage. 
- [ ] Ensure that all of our destructors get called properly at the end and that all of our memory gets deallocated. 

## Definition of done:
When the unit tests defined are capable of correctly catching any issues and throwing an error that signifies correctly any issue that may prevent the proper functioning of memory allocation and deallocation.

**Comment by KyleVaughn** [comment]
Review by @AvirupSircar

**Comment by AvirupSircar** [comment]
Looks fine. Though, It would be better to have the following additional tests:
1. Corner cases : Input of null matrix or single element or rectangular matrix
2. Construction/Destruction tests of all data types: float/ double
3. Tests for different pointers in C++. Class object created though Raw pointer and shared pointer. Use of new and delete in case of Raw and make_shared in case of shared ptr.
