### ISSUE TITLE
Add ELL view tests

### ISSUE THREAD

**Issue by KyleVaughn** [bkochuna/ners570f23-SpMV#57]
## Description:
Build a test for the ELL view function, it is a test for the view function of the `SparseMatrix_ELL` class and ensures that it does perform the task and ensures the functionality is correctly implemented.

## Tasks:

- [ ] Ensure that the ELL class has a view method defined
- [ ] Communicate with the ELL view method developed to understand the operation of the view method
- [ ] Ensure no bugs are present In the view function, assign a matrix to the ELL format to check functionality as well the required coefficients 
- [ ] Test the view method,  print output, if output matches expected output , view method passed, if not, view method implementation is incorrect. 
- [ ] IF the test fails, provide reason on screen

## Definition of done:
The ELL view test will work successfully and print the test results on the screen based on if the test passed or failed.

**Comment by sthvkbht** [comment]
Clear and detail plan of what is required for the issue. 👍

**Comment by sthvkbht** [comment]
The implementation compiles successfully and performs the defined tasks.
