### ISSUE TITLE
Create Extra Credit Issues

### ISSUE THREAD

**Issue by bkochuna** [bkochuna/ners570f23-SpMV#9]
## Background
There are several tasks that can be performed on this repository that involve some knowledge or skills not covered in depth in the course. These tasks are extra credit.

## Tasks
To complete this issue, the following new issues should be created.
 - [ ] Add continuous integration testing
 - [ ] Add code coverage testing
 - [ ] Add memory testing
 - [ ] Automatically generate sphinx documentation
 - [ ] Create a python interface to the library
 - [ ] Add integration to PETSc matrix types
 - [ ] Add project packaging
 - [ ] Add automated formating and linting checks for commits

## Definition of Done
The aforementioned issues have been created and accepted. To be accepted each issue should have a milestone, project and project status, and label.
